### ISSUE TITLE
fix api rout - /login-page 

### ISSUE THREAD

**Issue by codeholic-Samarth** [codeholic-aditya/blog_project#3]
@codeholic-aditya 
you have created the login rout end point /login-page, this is wrong, it has to be /login 
please fix it

**Comment by codeholic-aditya** [comment]
@codeholic-Samarth ,
okay i will fix it

**Comment by codeholic-aditya** [comment]
@codeholic-Samarth ,
"/login" is already set in the endpoint of route so to remove the conflict issue i have named "/login-page"

**Comment by codeholic-Samarth** [comment]
@codeholic-aditya 
okay
